In [4]:
import polars as pl

import nwec.utility_reporting.arrearages
import nwec.utils.excel
from nwec.constants import RAW_UTILITY_DATA, Utility

YEAR = 2024
QUARTER = 4
NUM_MONTHS = 3
COLS_PER_MONTH = 1
SHEET_SEARCH_STRING = "disconnections"
NUM_DISCONNECTIONS_SEARCH_STRING = "number of disconnections"
NUM_NOTICES_SEARCH_STRING = "number of customers by customer class receiving disconnection notices"
spreadsheet = RAW_UTILITY_DATA / str(YEAR) / f"{Utility.NWNG.code}_{YEAR}_Q{QUARTER}.xlsx"
source_date_format = "%Y-%m-%d %H:%M:%S"

In [5]:
sheet_index = nwec.utils.excel.get_sheet_index_from_name(spreadsheet, SHEET_SEARCH_STRING)
df = pl.read_excel(spreadsheet, sheet_id=sheet_index, has_header=False)
_, start_index = nwec.utils.excel.find_cell_by_string(df, NUM_DISCONNECTIONS_SEARCH_STRING)
disconnections = df.select(df.columns[start_index : start_index + NUM_MONTHS * COLS_PER_MONTH])

In [6]:
disconnections

shape: (133, 3)
┌─────────────────────────────────┬────────────┬────────────┐
│ column_4                        ┆ column_5   ┆ column_6   │
│ ---                             ┆ ---        ┆ ---        │
│ str                             ┆ str        ┆ str        │
╞═════════════════════════════════╪════════════╪════════════╡
│ Item a) Number of Disconnectio… ┆ null       ┆ null       │
│ null                            ┆ null       ┆ null       │
│ null                            ┆ null       ┆ null       │
│ COUNT_2410                      ┆ COUNT_2411 ┆ COUNT_2412 │
│ 0                               ┆ 0          ┆ 0          │
│ …                               ┆ …          ┆ …          │
│ 0                               ┆ 0          ┆ 0          │
│ 5                               ┆ 1          ┆ 2          │
│ 0                               ┆ 0          ┆ 0          │
│ 0                               ┆ 0          ┆ 0          │
│ 0                               ┆ 0          ┆ 0          │
└─────────────────────────────────┴────────────┴────────────┘

# Number of Disconnections

# Number of Disconnection Notices

In [7]:
_, start_index = nwec.utils.excel.find_cell_by_string(df, NUM_NOTICES_SEARCH_STRING)
notices = df.select(df.columns[start_index : start_index + NUM_MONTHS * COLS_PER_MONTH])

In [8]:
notices

shape: (133, 3)
┌─────────────────────────────────┬────────────┬────────────┐
│ column_21                       ┆ column_22  ┆ column_23  │
│ ---                             ┆ ---        ┆ ---        │
│ str                             ┆ str        ┆ str        │
╞═════════════════════════════════╪════════════╪════════════╡
│ Item c) Number of Customers by… ┆ null       ┆ null       │
│ null                            ┆ null       ┆ null       │
│ null                            ┆ null       ┆ null       │
│ COUNT_2410                      ┆ COUNT_2411 ┆ COUNT_2412 │
│ 0                               ┆ 0          ┆ 0          │
│ …                               ┆ …          ┆ …          │
│ 0                               ┆ 0          ┆ 0          │
│ 53                              ┆ 55         ┆ 123        │
│ 0                               ┆ 0          ┆ 0          │
│ 0                               ┆ 0          ┆ 0          │
│ 0                               ┆ 0          ┆ 0          │
└─────────────────────────────────┴────────────┴────────────┘