In [1]:
import polars as pl

import nwec.utility_reporting.arrearages
import nwec.utils.excel
from nwec.constants import RAW_UTILITY_DATA, Utility

YEAR = 2024
QUARTER = 4
NUM_MONTHS = 3
COLS_PER_MONTH = 1
SHEET_SEARCH_STRING = "disconnections"
NUM_DISCONNECTIONS_SEARCH_STRING = "number of disconnections"
NUM_NOTICES_SEARCH_STRING = "number of customers by customer class receiving disconnection notices"
spreadsheet = RAW_UTILITY_DATA / str(YEAR) / f"{Utility.PSE.code}_{YEAR}_Q{QUARTER}.xlsx"
source_date_format = "%Y-%m-%d %H:%M:%S"

In [2]:
sheet_index = nwec.utils.excel.get_sheet_index_from_name(spreadsheet, SHEET_SEARCH_STRING)
df = pl.read_excel(spreadsheet, sheet_id=sheet_index, has_header=False)
_, start_index = nwec.utils.excel.find_cell_by_string(df, NUM_DISCONNECTIONS_SEARCH_STRING)
disconnections = df.select(df.columns[start_index : start_index + NUM_MONTHS * COLS_PER_MONTH])

In [3]:
disconnections

shape: (440, 3)
┌──────────┬──────────┬──────────┐
│ column_3 ┆ column_4 ┆ column_5 │
│ ---      ┆ ---      ┆ ---      │
│ str      ┆ str      ┆ str      │
╞══════════╪══════════╪══════════╡
│ null     ┆ null     ┆ null     │
│ null     ┆ null     ┆ null     │
│ null     ┆ null     ┆ null     │
│ null     ┆ null     ┆ null     │
│ null     ┆ null     ┆ null     │
│ …        ┆ …        ┆ …        │
│ null     ┆ null     ┆ null     │
│ null     ┆ null     ┆ null     │
│ null     ┆ null     ┆ null     │
│ null     ┆ null     ┆ null     │
│ null     ┆ null     ┆ null     │
└──────────┴──────────┴──────────┘

# Number of Disconnections

# Number of Disconnection Notices

In [ ]:
_, start_index = nwec.utils.excel.find_cell_by_string(df, NUM_NOTICES_SEARCH_STRING)
notices = df.select(
    df.columns[start_index : start_index + NUM_MONTHS * COLS_PER_MONTH + 2]
)  # +2 to account for zip and customer class columns included

In [9]:
notices

shape: (440, 5)
┌───────────┬─────────────────────────────────┬───────────┬───────────┬───────────┐
│ column_13 ┆ column_14                       ┆ column_15 ┆ column_16 ┆ column_17 │
│ ---       ┆ ---                             ┆ ---       ┆ ---       ┆ ---       │
│ str       ┆ str                             ┆ str       ┆ str       ┆ str       │
╞═══════════╪═════════════════════════════════╪═══════════╪═══════════╪═══════════╡
│ null      ┆ null                            ┆ null      ┆ null      ┆ null      │
│ null      ┆ null                            ┆ null      ┆ null      ┆ null      │
│ null      ┆ null                            ┆ null      ┆ null      ┆ null      │
│ null      ┆ null                            ┆ null      ┆ null      ┆ null      │
│ null      ┆ null                            ┆ null      ┆ null      ┆ null      │
│ …         ┆ …                               ┆ …         ┆ …         ┆ …         │
│ 98943     ┆ Residential                   … ┆ 4         ┆ 8         ┆ 6         │
│ 98946     ┆ Commercial / Industrial       … ┆ null      ┆ null      ┆ 1         │
│ 98946     ┆ Residential                   … ┆ 2         ┆ 1         ┆ 1         │
│ (blanks)  ┆ Commercial / Industrial       … ┆ 3         ┆ 8         ┆ 5         │
│ (blanks)  ┆ Residential                   … ┆ 33        ┆ 39        ┆ 16        │
└───────────┴─────────────────────────────────┴───────────┴───────────┴───────────┘